### ISSUE TITLE
Create User Model

### ISSUE THREAD

**Issue by meta1203** [meta1203/CollegeCompendium-Backend#1]
Create a User Model that handles the following data:

- Username
- Email
- First name
- Last name
- Password (we might opt to use Spring Security for this)
- Links to account type (eg. a student user will be linked to a Student record)

Links with account type will likely need to be added as we add account types; feel free to ignore them for now

**Comment by Korbrent** [comment]
Instead of having User Model link to account type, have Student and other account types extend user
